### ISSUE TITLE
Typo: "Gemini AI ESP32 S2 for Flipper dev borard.zip" should be "board"

### ISSUE THREAD

**Issue by jamisonderek** [d4rks1d33/Gemini-Flipper#10]
https://github.com/d4rks1d33/Gemini-Flipper/blob/main/Gemini%20IA%20Precompiled%20binaries/Gemini%20AI%20ESP32%20S2%20for%20Flipper%20dev%20borard.zip has a typo. The word "borard" should be "board".

Actual: Gemini AI ESP32 S2 for Flipper dev borard.zip
Expect: Gemini AI ESP32 S2 for Flipper dev board.zip

**Comment by d4rks1d33** [comment]
Updated ^^
