### ISSUE TITLE
Contributors in README should more clearly call out d4rks1d3

### ISSUE THREAD

**Issue by jamisonderek** [d4rks1d33/Gemini-Flipper#11]
In the Contributors section of the readme, I think you should put https://github.com/d4rks1d33 as the top link, so it's clearer to people that you created the project. When reading from https://lab.flipper.net/apps/gemini_ia nobody knows you are the creator unless they click on repository link at the very bottom of the page.

**Comment by d4rks1d33** [comment]
Updated ^^
