### ISSUE TITLE
Slow install / first run.

### ISSUE THREAD

**Issue by jamisonderek** [d4rks1d33/Gemini-Flipper#13]
I doubt that people are going to download and extract the pre-installed ZIP file. Right now, it sort of hangs around 50% installed progress bar for a while because it is transferring such a large file & the first run of the app is slow as well while it extracts resources. I think it would be better for people to just install the firmware from github link & remove the precompiled binaries from the FAP.

Remove the following line from application.fam... 
   fap_file_assets="Gemini IA Precompiled binaries"

**Comment by d4rks1d33** [comment]
Updated ^^
