### ISSUE TITLE
Update the [ESP32] Gemini IA app for the SDK version 0.105 f7

### ISSUE THREAD

**Issue by furippa** [d4rks1d33/Gemini-Flipper#8]
Hello!

Your [ESP32] Gemini IA app version `0.1` fails to build with the SDK version `0.105.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/6734ca67efd94f9291462a1c/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/11820819183)

Flipper Team

**Comment by furippa** [comment]
I am again here!

Your [ESP32] Gemini IA app version `0.1` fails to build with the SDK version `1.0.1-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/6734ca67efd94f9291462a1c/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/11820819048)

Flipper Team

**Comment by d4rks1d33** [comment]
Hi, I'll check this and update the changes ASAP

Thanks ^^

**Comment by jamisonderek** [comment]
Delete the lines that have `text_input_set_minimum_length` and it should compile fine.

**Comment by Chickostick** [comment]
Okay Derek I apologize  in advance how do I remove the repository?
That way I don't keep messing things up

**Comment by d4rks1d33** [comment]
Updated ^^ should work now

**Comment by Chickostick** [comment]
Oh lol damn rookies lol I'll let the professionals  do there thing and step
aside
